name: HiPlugin
version: 3.2
main: top.whitecola.HiPlugin
author: [White_cola,Chloe030120]
commands:
  hip:
    usage: /hip <command> [args] ...
permissions:
  hiplugin.sayhi:
    default: op
  hiplugin.example:
    default: op